[tasks.init]
script = ['''
#!/usr/bin/env bash
cp -r config/* `acc config-dir`
''']

[tasks.new]
script = ['''
#!/usr/bin/env bash
cd contests/
acc new ${1} --choice none
''']

[tasks.add]
script = ['''
#!/usr/bin/env bash
cd contests/${1}
acc add --template cpp
''']

[tasks.test]
clear = true
script = ['''
#!/usr/bin/env bash
cd contests/${1}
g++ -std=gnu++17 main.cpp && oj t -d tests
''']

[tasks.submit]
script = ['''
#!/usr/bin/env bash
cd contests/${1}
acc submit main.cpp -- -y
''']
